#!/usr/bin/env bash
# Script that installs nginx serve and configures it to listen on port 80.
# print "Hello World!"

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
