#!/usr/bin/env bash
# Script that installs nginx serve and configures it to listen on port 80.
# print "Hello World!"

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me hhtps:\/\/github.com\/Samuelibudi permanent;/" /etc/nginx/sites-available/default
sudo service nginx start
