#!/bin/env bash
#Script installs nginx and configures it to listen to port 80
sudo apt update
sudo apt install nginx -y
sudo sed -i 's/# listen 80/listen 80/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80 deefault_server;/listen [::]:80 default_server;\n
sudo systemctl restart nginx
