#!/usr/bin/env bash
# A script that displays Best school 10 times.
min=1
hr=0
while [ $hr -le 12 ]
do
	echo "Hour: $hr"
	while [ $min -le 59 ]
	do
		echo "$min"
		min=$(( min + 1 ))
	done
	min=1
	hr=$(( hr + 1 ))
done
